### ISSUE TITLE
EU Mobile Number

### ISSUE THREAD

**Issue by edwardjblake** [HalfaHeartLeft/Hyper-Cart#2]
Most phone numbers ( inlcuding UK) in EU are just one number no "-" anywhere, therefore the system of entering the different parts of the phone number doesn't seem to be working for me, is there a possible solution to this?
thanks

**Comment by HalfaHeartLeft** [comment]
Will do! Update 2.0 is coming out soon! Going completely rework it and make it alot more pretty and get rid of any bugs!

**Comment by HalfaHeartLeft** [comment]
Fixed my friend :)
